name: gauges
description: A library for customizable gauges (radial gauges only for now).
version: 1.0.0
homepage: https://www.julianassmann.de/
repository: https://github.com/JulianAssmann/flutter_gauges

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
